'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SchlumpfSoft.ExtensionsDemo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deme der Erweiterungsfunktionen DifferenceOf
        '''============================================
        '''
        '''Diese Erweiterung berechnet die Differenz zwischen dem 
        '''aktuellen Wert und einem angegebenen Wert.
        '''
        '''Unterstützte Typen:
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double  
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property DifferenceOf_InfoText() As String
            Get
                Return ResourceManager.GetString("DifferenceOf_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktion FractionBy
        '''========================================
        '''
        '''Berechnet den Bruchteil eines Wertes basierend auf einem Prozentsatz.
        '''
        '''Unterstützte Typen:
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double.
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property FractionBy_InfoText() As String
            Get
                Return ResourceManager.GetString("FractionBy_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktionen IsDivisibleBy
        '''=============================================
        '''
        '''Diese Erweiterung überprüft, ob der übergebene Wert ohne Rest 
        '''durch den angegebenen Divisor teilbar ist.
        '''
        '''Unterstützte Typen:
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property IsDivisibleBy_InfoText() As String
            Get
                Return ResourceManager.GetString("IsDivisibleBy_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktionen IsInRangeOf
        '''===========================================
        '''
        '''Diese erweterung überprüft, ob der angegebene Wert innerhalb 
        '''des angegebenen Bereichs liegt.
        '''
        '''Unterstützte Typen:
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double  
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property IsInRangeOf_InfoText() As String
            Get
                Return ResourceManager.GetString("IsInRangeOf_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktionen IsMultibleOf
        '''============================================
        '''
        '''Diese Erweiterung überprüft, ob der übergebene Wert ein Vielfaches
        '''des angegebenen Wertes ist.
        '''
        '''Unterstützte Typen:
        '''Short, Ushort, Integer, UInteger, Long, ULong, Decimal, Single, Double
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property IsMultipleOf_InfoText() As String
            Get
                Return ResourceManager.GetString("IsMultipleOf_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktionen IsPrime
        '''======================================
        '''
        '''Diese Funktionen testet ob ein Wert eine Primzahl ist.
        '''
        '''Unterstützte Typen:
        '''Short, UShort, Integer, UInteger, Long.
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property IsPrime_InfoText() As String
            Get
                Return ResourceManager.GetString("IsPrime_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktion PercentageOf
        '''==========================================
        '''
        '''Berechnet den Prozentsatz eines Wertes im Verhältnis zu einem Gesamtwert.
        '''
        '''Unterstützte Typen: 
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double.
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property PercentageOf_InfoText() As String
            Get
                Return ResourceManager.GetString("PercentageOf_InfoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Demo der Erweiterungsfunktinen isPositive und isNegative
        '''========================================================
        '''
        '''Diese Funktionen testet ob ein Wert positiv oder negativ ist.
        '''
        '''Unterstützte Typen: 
        '''Short, UShort, Integer, UInteger, Long, ULong, Decimal, Single, Double.
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property SignTest_InfoText() As String
            Get
                Return ResourceManager.GetString("SignTest_InfoText", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
